// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef add_model_h
#define add_model_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *edit_mod_win;
#include <FL/Fl_Group.H>
extern Fl_Group *mod_type_group;
#include <FL/Fl_Round_Button.H>
extern Fl_Round_Button *reg_bok_rbtn;
extern Fl_Round_Button *til_bok_rbtn;
extern Fl_Round_Button *sph_rbtn;
extern Fl_Round_Button *int_face_rbtn;
extern Fl_Group *val_type_group;
extern Fl_Round_Button *app_val_rbtn;
extern Fl_Round_Button *rep_val_rbtn;
extern Fl_Round_Button *era_val_rbtn;
extern Fl_Group *agn_part_group;
extern Fl_Round_Button *top_val_btn;
extern Fl_Round_Button *bot_val_btn;
#include <FL/Fl_Input.H>
extern Fl_Input *sig_mod_para_input;
extern Fl_Input *mod_val_input;
#include <FL/Fl_Button.H>
extern Fl_Button *sig_add_btn;
extern Fl_Button *sig_replace_btn;
extern Fl_Button *sig_delete_btn;
#include <FL/Fl_Return_Button.H>
extern Fl_Return_Button *can_add_btn;
void cb_add_mod_btn(Fl_Button*, void*);
#endif
