#include "gm3d_gui.h"

Fl_Double_Window *main_window=(Fl_Double_Window *)0;
Fl_Tabs *main_tabs=(Fl_Tabs *)0;
Fl_Group *model_tab=(Fl_Group *)0;
Fl_Input *mesh_para_input=(Fl_Input *)0;
Fl_Button *mesh_file_btn=(Fl_Button *)0;
Fl_Button *mod_para_file_btn=(Fl_Button *)0;
Fl_Input *mod_ele_input_build=(Fl_Input *)0;
Fl_Button *build_mod_btn=(Fl_Button *)0;
Fl_Output *mesh_para_output=(Fl_Output *)0;
Fl_Button *add_mod_btn=(Fl_Button *)0;
Fl_Button *del_mod_btn=(Fl_Button *)0;
Fl_Check_Button *rm_emp_bok_check=(Fl_Check_Button *)0;
Fl_Browser *mod_para_brw=(Fl_Browser *)0;
Fl_Button *mod_file_out_btn=(Fl_Button *)0;
Fl_Output *mod_out_file_output=(Fl_Output *)0;
Fl_Group *forward_tab=(Fl_Group *)0;
Fl_Group *grav_group=(Fl_Group *)0;
Fl_Check_Button *Vz_check=(Fl_Check_Button *)0;
Fl_Check_Button *Vzx_check=(Fl_Check_Button *)0;
Fl_Check_Button *Vzy_check=(Fl_Check_Button *)0;
Fl_Check_Button *Vzz_check=(Fl_Check_Button *)0;
Fl_Button *mod_file_btn=(Fl_Button *)0;
Fl_Button *obs_file_btn=(Fl_Button *)0;
Fl_Input *mod_file_input=(Fl_Input *)0;
Fl_Output *mod_file_output=(Fl_Output *)0;
Fl_Input *obs_file_input=(Fl_Input *)0;
Fl_Output *obs_file_output=(Fl_Output *)0;
Fl_Input *mod_ele_input=(Fl_Input *)0;
Fl_Group *mag_group=(Fl_Group *)0;
Fl_Check_Button *DeltaT_check=(Fl_Check_Button *)0;
Fl_Check_Button *DeltaTx_check=(Fl_Check_Button *)0;
Fl_Check_Button *DeltaTy_check=(Fl_Check_Button *)0;
Fl_Check_Button *DeltaTz_check=(Fl_Check_Button *)0;
Fl_Check_Button *Hax_check=(Fl_Check_Button *)0;
Fl_Check_Button *Hay_check=(Fl_Check_Button *)0;
Fl_Check_Button *Za_check=(Fl_Check_Button *)0;
Fl_Input *mag_para_input=(Fl_Input *)0;
Fl_Check_Button *mag_data_check=(Fl_Check_Button *)0;
Fl_Button *cal_btn=(Fl_Button *)0;
Fl_Input *noise_para_input=(Fl_Input *)0;
Fl_Check_Button *noise_check=(Fl_Check_Button *)0;
Fl_Input *res_file_input=(Fl_Input *)0;
Fl_Button *res_file_btn=(Fl_Button *)0;
Fl_Output *res_out_file_output=(Fl_Output *)0;

void cb_mesh_para_input(Fl_Input*, void*){}
void cb_mesh_file_btn(Fl_Widget*, void*){}
void cb_add_mod_btn(Fl_Widget*, void*){}
void cb_mod_para_file_btn(Fl_Widget*, void*){}
void cb_del_mod_btn(Fl_Widget*, void*){}
void cb_mod_para_brw(Fl_Browser*, void*){}
void cb_mod_ele_input(Fl_Input*, void*){}
void cb_rm_emp_bok_check(Fl_Check_Button*, void*){}
void cb_mod_file_out_btn(Fl_Widget*, void*){}
void cb_build_mod_btn(Fl_Widget*, void*){}
void cb_mod_file_input(Fl_Input*, void*){}
void cb_mod_file_btn(Fl_Widget*, void*){}
void cb_obs_file_input(Fl_Input*, void*){}
void cb_obs_file_btn(Fl_Widget*, void*){}
void cb_res_file_input(Fl_Input*, void*){}
void cb_res_file_btn(Fl_Widget*, void*){}
void cb_nosie_check(Fl_Check_Button*, void*){}
void cb_noise_para_input(Fl_Input*, void*){}
void cb_mag_data_check(Fl_Check_Button*, void*){}
void cb_mag_para_input(Fl_Input*, void*){}
void cb_cal_btn(Fl_Button*, void*){}
void cb_noise_check(Fl_Check_Button*, void*){}